export const inputList = {
	game: "",
	cardType: "",
	name: "",
	difficulty: "",
	damage: 0,
	attackZone: "",
	blockZone: "",
	speed: 0,
	control: 0,
	blockMod: 0,
	origin: "",
	attributes: ["Air", "Fire", "Water", "All"],
	text: "",
};
